feat/#10:Header컴포넌트 추가
S0PTerest/S0PTerest-Client pull request #17
Opened 2022-11-18 10:21 UTC by hyunwookchung

## ⛓ Related Issues

- close feat/#10

## 😖feat/#10

## 📋 작업 내용

- [x]  Header 컴포넌트 ui 구현
- [x]  Heder 컴포넌트 구조화 및 스타일링

## 📌 PR Point

DropBox 를 사용하여 Header 에 두곳에 적용을 시켜주었는데요, 포지션과 위치가 고정되어 있어
배치를 원하는곳에 할수 없어서 프롭스로 넘겨주어 팀원들이 각자 원하는 위치에 DropBox를 

유동적으로배치 할수 있게 수정해보았습니다.

다른사람과 같이 작업 한 적이 처음이라, 제 선택으로 다른 팀원들이 어떤 위험이나 우려가 발생될진

예측을 잘못하겠습니다, 혹여 제 선택으로 다른 팀원들에게 어떤 영향을 끼치게 알려주시면 …ㅎㅎㅎ

프롭스에 관한 부분에 대해 리뷰어분이 집중해주셨으면 좋겠어요, 협업 할때 플로우를 전혀 몰라
아는 개발자 분이 감잡으라고 같이 알려주셨는데요, 타인이 만든 컴포넌트를 제 코드에 적용 시켜본적이 경험이 처음이라서 제가 만든 컴포넌트라면 어디에 어떻게 쓰일지 미리 생각하고 만들었기에

완성된 컴포넌트를 다시 수정할 일이 없었습니다, 근데 하나의 컴포넌트로 다른 팀원들과 같이 사용하려면 각자의 작업이 다 다르기에 자기 작업에 맞게 조금씩 수정이 필요하잖아요, 그 부분에 피드백을 주시면 열심히 다시 연구해보겠습니다 감사합니다.  

아 마지막으로 협업할때 제가 미숙한 부분이나 아쉬운 부분이 있으시면 피드백 해주세요, 빠른 
시일 내 참고하여 적용해보겠습니다! 
![image](https://user-images.githubusercontent.com/109159539/202679293-69f611c7-da67-4b61-a211-81f541ed99f9.png)

## 제가 만든 Header 랍니다~ㅎㅎ

2022-11-18 11:06 UTC, talkingOrange requested changes
완전 잘 했네!!!!!
Logo는 우리가 클릭 시에 메인으로 이동하는 기능을 따로 가져야하니까
import { ReactComponent as IconLogo } from '경로.svg';
일케 import해서 <IconLogo onClick={}/>기능 추가하는걸로 해주면 좋을 것 같아~!!! 고생했다~!!!

2022-11-18 12:47 UTC, leeseooo requested changes
굿굿 고생했어!!👍👍👍👍👍👍👍
 코멘트 몇개 달아놨는데 확인해주고 수정 부탁할게!

2022-11-18 12:47 UTC, leeseooo commented on src/components/common/DropBox.jsx
> +  const { text, options, top, right } = props;
이렇게 props로 요소의 위치를 넘겨주는 것보다는 text에 따라 다른 css를 적용하는 방식이 더 나을 것 같어
컴포넌트의 재사용성을 생각하면 꼭 필요한 것들만 props로 넘겨주는 게 맞다고 생각하거든

```jsx
const { text, options } = props;

  const dropBoxStatus = {
    '노트 옵션': css`
      top: 5.1rem;
      right: -11rem;
      background-color: red;
    `,

    알파벳순: css`
      background-color: black;
      top: 3rem;
      right: 10rem;
    `,
  };

 return (
    <StyledRoot status={dropBoxStatus[text]}>
      <StyledText>{text}</StyledText>
      {options.map((option) => (
        <StyledOption key={option}>{option}</StyledOption>
      ))}
    </StyledRoot>
  );


```
이거 림이가 카톡으로 질문해줬던 거에 답변한 건데 이거 참고해서 수정해볼래?
`dropBoxStatus`라는 객체는 '노트 옵션', '알파벳순'을 key로 가지고 있고 각 옵션에 따른 css를 value값으로 가지고 있어. 오빠가 필요한 건 '만들기' 니까 key,value쌍을 하나 더 추가하면 될 것 같아

2022-11-18 12:47 UTC, leeseooo commented on src/components/common/Header.jsx
> +        <StyledArrow src={isRecommendOpen ? IconArrowUp : IconArrowDown} />
이것도 잘 하긴 했는데 나라면 `StyledArrow` 태그의 props로 isRecommendOpen 을 넘겨준 다음
transform 속성의 rotate를 적용할 것 같아. -> [참고링크](https://developer.mozilla.org/ko/docs/Web/CSS/transform)
굳이 이미지를 하나 더 쓰기보다는 css속성을 사용해서 불필요한 이미지를 줄일 수 있을 것 같어

2022-11-18 12:47 UTC, leeseooo commented on src/components/common/Header.jsx
> +    <StyledHeaderWrapper>
우리 최상위 태그는 `StyledRoot`로 쓰는게 컨벤션이야

2022-11-18 12:47 UTC, leeseooo commented on src/components/common/Header.jsx
> +  const [isAddOpen, setIsAddOpen] = React.useState(false);
useState를 굳이 React.useState로 쓰지않고 
```jsx 
import React, {useState} from 'react';
```
로 써주면 훨씬 깔끔할듯

2022-11-18 12:47 UTC, leeseooo commented on src/components/common/Header.jsx
> +  const options = ['보드이름', '보드이름1', '보드이름2'];
요거는 추천옵션 드롭박스용 상수 하나, 만들기 드롭박스용 상수 하나 해서 두개의 객체를 만들면 어떨까
```jsx
const RECOMMEND_OPTION= {
  title: '추천옵션',
  options: ['핀', '아이디어핀', '보드'],
};
const MAKE_OPTION= {
  title: '추천옵션',
  options: ['보드이름', '보드이름1', '보드이름2''],
}
```
머 이런식으로?

2022-11-18 12:47 UTC, leeseooo commented on src/components/common/Header.jsx
> +          )}
`만들기` 라는 기능에 대해 네이밍이 여러개로 분산된 느낌이 드네
add 랑 make 중에서 하나만 쓰는게 혼란을 줄일 수 있을 것 같아

2022-11-18 12:47 UTC, leeseooo commented on src/components/common/Header.jsx
> +const StyledIconMessage = styled.div``;
안쓰는 스타일 컴포넌트들은 삭제해주고 시멘틱 태그로 써줘도 될 것 같아

2022-11-18 12:47 UTC, leeseooo commented on src/components/common/Header.jsx
> +  position: relative;
요거는 없어도 동작할 것 같다

2022-11-23 14:31 UTC, hyunwookchung commented
> 굿굿 고생했어!!👍👍👍👍👍👍👍 코멘트 몇개 달아놨는데 확인해주고 수정 부탁할게!

바로 확인해보겠습니다~

2022-11-24 10:37 UTC, leeseooo requested changes

2022-11-24 10:37 UTC, leeseooo commented on src/components/common/Header.jsx
> +};
상수 이름 좋은데 약간 읽기 힘드니까 언더바( _ ) 를 붙여서 좀 띄워주면 어떨까요

2022-11-24 10:37 UTC, leeseooo commented on src/components/common/Header.jsx
> +          console.log(searchText);
콘솔은 다 지워주라!

2022-11-24 10:37 UTC, leeseooo commented on src/components/common/Header.jsx
> +const StyledIconNotice = styled.div``;
사용하지 않는 스타일 컴포넌트는 지워주라!

2022-11-24 10:37 UTC, leeseooo commented on src/components/common/DropBox.jsx
> +  console.log(text);
여기 콘솔도 지워주라

2022-11-24 13:09 UTC, leeseooo approved these changes
고생했어! 이제 예원이 보드 UI 가져다가 붙이기만 하면 되겠다

2022-11-24 13:54 UTC, talkingOrange approved these changes

2022-11-24 13:57 UTC, merged